### ISSUE TITLE
[OpenCL] clBuildProgram Failed. __kernel function cannot have argument whose type is, or contains, type size_t.

### ISSUE THREAD

**Issue by terminal-oni** [pytorch/glow#1076] opened 2018-05-24 17:29 UTC
Here is the `clinfo` output for my system [pastebin](https://pastebin.com/6xgiBS85)

I've compiled `glow` with OpenCL support as follows
```
$ cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DGLOW_WITH_CPU=1 -DGLOW_WITH_OPENCL=1  ../glow
$ ninja all
```
Whenever I try to run any of the unittests or demos with the `-opencl` command line option, I get : 
```
<kernel>:282:1: error: unexpected type name 'vtype': expected expression
DEFINE_OPENCL_UNARY_DATA_PARALLEL_KERNEL_WITH_IMM_OPERAND(splat, float, SRC)
^
<kernel>:240:19: note: expanded from macro 'DEFINE_OPENCL_UNARY_DATA_PARALLEL_KERNEL_WITH_IMM_OPERAND'
      vtype SRC = vtype(val);                                                  \
                  ^
<kernel>:283:1: error: unexpected type name 'vtype': expected expression
DEFINE_OPENCL_UNARY_DATA_PARALLEL_KERNEL_WITH_IMM_OPERAND(splat_u, ulong, SRC)
^
<kernel>:240:19: note: expanded from macro 'DEFINE_OPENCL_UNARY_DATA_PARALLEL_KERNEL_WITH_IMM_OPERAND'
      vtype SRC = vtype(val);                                                  \
                  ^
<kernel>:334:59: error: __kernel function cannot have argument whose type is, or contains, type size_t
                                cl_uint32_t batch, size_t numSlice,
                                                          ^
<kernel>:335:40: error: __kernel function cannot have argument whose type is, or contains, type size_ta
                                size_t sliceSize) {
                                       ^

/glow/lib/Backends/OpenCL/OpenCL.cpp:189: failed assertion `err == CL_SUCCESS && "clBuildProgram Failed."'
```
I'm far from conversant in OpenCL but I made the changes that the compiler highlights
```
diff --git a/lib/Backends/OpenCL/kernels.cl b/lib/Backends/OpenCL/kernels.cl
index f51a1267..17b96644 100644
--- a/lib/Backends/OpenCL/kernels.cl
+++ b/lib/Backends/OpenCL/kernels.cl
@@ -238,7 +238,7 @@ size_t getNCHW(ShapeNCHW s, cl_uint32_t n, cl_uint32_t c, cl_uint32_t h,
       vstore8(VAL, i * 2, dest);                                               \
     }                                                                          \
     {                                                                          \
-      vtype SRC = vtype(val);                                                  \
+      vtype SRC = (vtype)val;                                                  \
       vtype VAL = body;                                                        \
       vstore8(VAL, i * 2 + 1, dest);                                           \
     }                                                                          \
@@ -332,8 +332,8 @@ __kernel void batchedreduceaddK(__global float *dest, __global float *batch,
 }
 
 __kernel void batchedreduceaddW(__global void *mem, cl_uint32_t dest,
-                                cl_uint32_t batch, size_t numSlice,
-                                size_t sliceSize) {
+                                cl_uint32_t batch, cl_uint32_t numSlice,
+                                cl_uint32_t sliceSize) {
   batchedreduceaddK(&mem[dest], &mem[batch], numSlice, sliceSize);
 }

```

Now, `OCLTest`, `MLTest`, `ptb` all work fine with OpenCL backend but `operatorTest`, `JITTest` and `mnist` all fail certain tests.

```
[ RUN      ] OpenCL/Operator.simplePredication/0
glow/lib/Backends/OpenCL/OpenCL.cpp:197: failed assertion `err == CL_SUCCESS && "Unable to set parameter"'
[ RUN      ] OpenCL/BackendCorrectnessTest.poolMaxGradTest/0
glow/lib/Backends/OpenCL/OpenCL.cpp:197: failed assertion `err == CL_SUCCESS && "Unable to set parameter"'
$ ./bin/mnist -opencl
Loading the mnist database.
Loaded 50000 images.
Training.
Training - epoch #0
glow/lib/Backends/OpenCL/OpenCL.cpp:197: failed assertion `err == CL_SUCCESS && "Unable to set parameter"'

```

How can I resolve this?

**Comment by opti-mix** [comment] 2018-05-24 17:49
@terminal-oni Good catch regarding the usage of `size_t`! Thanks for reporting it! We'll fix it ASAP.

**Comment by opti-mix** [comment] 2018-05-24 18:29
@terminal-oni The type casts related issues should be fixed by #1077.

But I cannot reproduce your test failures with `operatorTest`,`JITTest` and `mnist`. It could be due to the fact that you use NVidia and I test with AMD Radeon.

BTW, do you have multiple OpenCL devices available on your machine? E.g. the CPU itself is also considered to be an OpenCL device on MacBooks. There is an option called `-device` that you can use to pick a specific OpenCL device. This option takes a device number as a parameter. By default the device number 0 is assumed.

**Comment by terminal-oni** [comment] 2018-05-24 18:41
I'm on Arch Linux, and I only have a single OpenCL device available (GPU, GeForce 840M).
(Both `clinfo` and `/etc/OpenCL/vendors/` lists only the Nvidia GPU ICD as available).

**Comment by opti-mix** [comment] 2018-05-24 19:19
Since I cannot reproduce locally, I'd need your help. Could you try to run the `operatorTest` using a debugger and when it asserts you try to use the backtrace to find which parameters cannot be set, i.e. which kernel, which parameter number, which value?

**Comment by terminal-oni** [comment] 2018-05-24 20:37
I ran the failing executables through gdb and in almost all of them, `OpenCL.cpp:875` appears to be the culprit. In `OCLBackend::doForwardPass()` at line 875 there is a call to `setKernelArg<size_t>(...)`.
This appeared suspicious, so changing it to `cl_uint` and recompiled. All the examples including `mnist` and `cifar` now seem to work fine!

**Closed** 2018-05-24 21:07 UTC
