### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by idreamboat** [pytorch/glow#2083] opened 2018-11-27 07:19 UTC
my macOS is Mojave 10.14 
I try to install in my mac follow the step:
1. git clone https://github.com/pytorch/glow
2. cd glow
3. git submodule update --init --recursive
4. brew install cmake graphviz libpng ninja protobuf wget
5. brew install --with-toolchain llvm@6
  prmkdir build_Debug
cd build_Debugevious step is all ok , but in the **Configure and build**
  due to my llvm and cmake are in other path so
6. 1 `mkdir build_Debug`
6.2 `cd build_Debug`
6.3 ` /usr/local/Cellar/cmake/3.13.0/bin/cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug  -DCMAKE_PREFIX_PATH=/usr/local/Cellar/llvm@6/6.0.1_1/  ../glow`
  step 6 is ok, log as follow

```
CMake Warning at CMakeLists.txt:65 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "7".

  The following configuration files were considered but not accepted:

    /usr/local/Cellar/llvm@6/6.0.1_1/lib/cmake/llvm/LLVMConfig.cmake, version: 6.0.1
    /usr/local/Cellar/llvm@6/6.0.1_1/lib/cmake/llvm/llvm-config.cmake, version: unknown



-- Found LLVM 6.0.1
-- Using LLVMConfig.cmake in: /usr/local/Cellar/llvm@6/6.0.1_1/lib/cmake/llvm
--
-- ******** Summary ********
--   CMake version         : 3.13.0
--   CMake command         : /usr/local/Cellar/cmake/3.13.0/bin/cmake
--   System                : Darwin
--   C++ compiler          : /Library/Developer/CommandLineTools/usr/bin/c++
--   C++ compiler version  : 10.0.0.10001044
--   CXX flags             :  -Wall -Wnon-virtual-dtor -fno-exceptions -fno-rtti -Wnon-virtual-dtor
--   Build type            : Debug
--   Compile definitions   : WITH_PNG;GLOW_WITH_CPU=1;GLOW_WITH_OPENCL=1;GOOGLE_PROTOBUF_NO_RTTI;ONNX_NAMESPACE=glow_onnx
--   CMAKE_PREFIX_PATH     : /usr/local/Cellar/llvm@6/6.0.1_1/
--   CMAKE_INSTALL_PREFIX  : /usr/local
--   CMAKE_MODULE_PATH     : /Users/iDreamboat/Documents/Typora/ml_sklearn_tf/glow_no_env/glow/cmake/modules
--
--   ONNX version          : 1.3.0
--   ONNX NAMESPACE        : glow_onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--
--   Protobuf compiler     : /usr/local/bin/protoc
--   Protobuf includes     : /usr/local/include
--   Protobuf libraries    : /usr/local/lib/libprotobuf.dylib
--   BUILD_ONNX_PYTHON     : OFF
CMake Warning (dev) at tests/unittests/CMakeLists.txt:242 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  An interface source of target "BackendCorrectnessTest" has a relative path.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/iDreamboat/Documents/Typora/ml_sklearn_tf/glow_no_env/glow/build_Debug
```

7. `ninja all` 
  step 7 are problem, log as follow.

  ```
  [2/80] Linking CXX executable tests/graphSchedulerTest
  ld: warning: ignoring file /Library/Frameworks//libpng.framework/libpng, missing required architecture x86_64 in file /Library/Frameworks//libpng.framework/libpng (2 slices)
  [3/80] Linking CXX executable tests/graphOptzTest
  ld: warning: ignoring file /Library/Frameworks//libpng.framework/libpng, missing required architecture x86_64 in file /Library/Frameworks//libpng.framework/libpng (2 slices)
  [6/80] Linking CXX executable tests/IROptTest
  ld: warning: ignoring file /Library/Frameworks//libpng.framework/libpng, missing required architecture x86_64 in file /Library/Frameworks//libpng.framework/libpng (2 slices)
  [8/80] Linking CXX executable tests/imageTest
  FAILED: tests/imageTest
  : && /Library/Developer/CommandLineTools/usr/bin/c++  -Wall -Wnon-virtual-dtor -fno-exceptions -fno-rtti -g -fno-omit-frame-pointer -O0 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  tests/unittests/CMakeFiles/imageTest.dir/imageTest.cpp.o  -o tests/imageTest  lib/Base/libBase.a tests/googletest/googlemock/gtest/libgtestd.a tests/unittests/libtestMain.a lib/Support/libSupport.a -framework libpng tests/googletest/googlemock/gtest/libgtestd.a /usr/local/Cellar/llvm@6/6.0.1_1/lib/libLLVMSupport.a -lz -lcurses -lm /usr/local/Cellar/llvm@6/6.0.1_1/lib/libLLVMDemangle.a && :
  ld: warning: ignoring file /Library/Frameworks//libpng.framework/libpng, missing required architecture x86_64 in file /Library/Frameworks//libpng.framework/libpng (2 slices)
  Undefined symbols for architecture x86_64:
    "_png_create_info_struct", referenced from:
        glow::getPngInfo(char const*) in libBase.a(Image.cpp.o)
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
        glow::writePngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_create_read_struct", referenced from:
        glow::getPngInfo(char const*) in libBase.a(Image.cpp.o)
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_create_write_struct", referenced from:
        glow::writePngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_destroy_read_struct", referenced from:
        glow::getPngInfo(char const*) in libBase.a(Image.cpp.o)
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_destroy_write_struct", referenced from:
        glow::writePngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_get_bit_depth", referenced from:
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_get_color_type", referenced from:
        glow::getPngInfo(char const*) in libBase.a(Image.cpp.o)
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_get_image_height", referenced from:
        glow::getPngInfo(char const*) in libBase.a(Image.cpp.o)
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_get_image_width", referenced from:
        glow::getPngInfo(char const*) in libBase.a(Image.cpp.o)
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_get_rowbytes", referenced from:
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
        glow::writePngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_init_io", referenced from:
        glow::getPngInfo(char const*) in libBase.a(Image.cpp.o)
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
        glow::writePngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_read_end", referenced from:
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_read_image", referenced from:
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_read_info", referenced from:
        glow::getPngInfo(char const*) in libBase.a(Image.cpp.o)
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_read_update_info", referenced from:
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_set_IHDR", referenced from:
        glow::writePngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_set_interlace_handling", referenced from:
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_set_longjmp_fn", referenced from:
        glow::getPngInfo(char const*) in libBase.a(Image.cpp.o)
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
        glow::writePngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_set_sig_bytes", referenced from:
        glow::getPngInfo(char const*) in libBase.a(Image.cpp.o)
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_sig_cmp", referenced from:
        glow::getPngInfo(char const*) in libBase.a(Image.cpp.o)
        glow::readPngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_write_end", referenced from:
        glow::writePngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_write_image", referenced from:
        glow::writePngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
    "_png_write_info", referenced from:
        glow::writePngImage(glow::Tensor*, char const*, std::__1::pair<float, float>, bool) in libBase.a(Image.cpp.o)
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  [14/80] Linking CXX executable tests/typeAToTypeBFunctionConverterTest
  ld: warning: text-based stub file /System/Library/Frameworks//OpenCL.framework/OpenCL.tbd and library file /System/Library/Frameworks//OpenCL.framework/OpenCL are out of sync. Falling back to library file for linking.
  ld: warning: ignoring file /Library/Frameworks//libpng.framework/libpng, missing required architecture x86_64 in file /Library/Frameworks//libpng.framework/libpng (2 slices)
  [17/80] Building CXX object tests/unittests/CMakeFiles/operatorTest.dir/OperatorTest.cpp.o
  ninja: build stopped: subcommand failed.
  ```

**Comment by nadavrot** [comment] 2018-11-27 17:41
The error message is strange:

ld: warning: ignoring file /Library/Frameworks//libpng.framework/libpng, missing required architecture x86_64 in file /Library/Frameworks//libpng.framework/libpng

It looks like we are trying to link the libpng framework but for some reason this file does not have the x86_64 slice (or does not exist!)

I don't have this file on my system. My build does not use the libpng framework, just the library. I wonder if this is a new regression.

**Comment by bertmaher** [comment] 2018-11-27 18:20
Could remove your build directory, run cmake again, and send the complete log?  I'm particularly interested in the line of output where it locates `libpng`.  For me this looks like:
```
-- Found PNG: /usr/local/lib/libpng.dylib (found version "1.6.34")
```

**Comment by bertmaher** [comment] 2018-11-27 18:38
Something that might work to give Homebrew's libpng precedence in your build is to explicitly export CMAKE_PREFIX_PATH into your environment before running CMake.
```
export CMAKE_PREFIX_PATH=/usr/local:/usr/local/Cellar/llvm@6/6.0.1_1
cmake  -G Ninja -DCMAKE_BUILD_TYPE=Debug ../glow
```

CMake checks the environment-specified prefix-path before anything specified on the command line.

**Comment by idreamboat** [comment] 2018-11-28 02:46
> Could remove your build directory, run cmake again, and send the complete log? I'm particularly interested in the line of output where it locates `libpng`. For me this looks like:
> 
> ```
> -- Found PNG: /usr/local/lib/libpng.dylib (found version "1.6.34")
> ```

```
ChangdeMacBook-Pro:build_Debug iDreamboat$ /usr/local/Cellar/cmake/3.13.0/bin/cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=/usr/local/Cellar/llvm@6/6.0.1_1/ ../../glow
-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Tests not explicitly enabled/disabled, default to enable
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.3")
-- Found PNG: /Library/Frameworks/libpng.framework
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: /System/Library/Frameworks/OpenCL.framework (found version "1.2")
CMake Warning at CMakeLists.txt:65 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "7".

  The following configuration files were considered but not accepted:

    /usr/local/Cellar/llvm@6/6.0.1_1/lib/cmake/llvm/LLVMConfig.cmake, version: 6.0.1
    /usr/local/Cellar/llvm@6/6.0.1_1/lib/cmake/llvm/llvm-config.cmake, version: unknown



-- Found LLVM 6.0.1
-- Using LLVMConfig.cmake in: /usr/local/Cellar/llvm@6/6.0.1_1/lib/cmake/llvm
-- Found Protobuf: /usr/local/lib/libprotobuf.dylib (found version "3.6.1")
--
-- ******** Summary ********
--   CMake version         : 3.13.0
--   CMake command         : /usr/local/Cellar/cmake/3.13.0/bin/cmake
--   System                : Darwin
--   C++ compiler          : /Library/Developer/CommandLineTools/usr/bin/c++
--   C++ compiler version  : 10.0.0.10001044
--   CXX flags             :  -Wall -Wnon-virtual-dtor -fno-exceptions -fno-rtti -Wnon-virtual-dtor
--   Build type            : Debug
--   Compile definitions   : WITH_PNG;GLOW_WITH_CPU=1;GLOW_WITH_OPENCL=1;GOOGLE_PROTOBUF_NO_RTTI;ONNX_NAMESPACE=glow_onnx
--   CMAKE_PREFIX_PATH     : /usr/local/Cellar/llvm@6/6.0.1_1/
--   CMAKE_INSTALL_PREFIX  : /usr/local
--   CMAKE_MODULE_PATH     : /Users/iDreamboat/Documents/Typora/ml_sklearn_tf/glow_no_env/glow/cmake/modules
--
--   ONNX version          : 1.3.0
--   ONNX NAMESPACE        : glow_onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--
--   Protobuf compiler     : /usr/local/bin/protoc
--   Protobuf includes     : /usr/local/include
--   Protobuf libraries    : /usr/local/lib/libprotobuf.dylib
--   BUILD_ONNX_PYTHON     : OFF
-- Found PythonInterp: /Library/Frameworks/Python.framework/Versions/2.7/bin/python (found version "2.7.15")
-- Found Threads: TRUE
CMake Warning (dev) at tests/unittests/CMakeLists.txt:242 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  An interface source of target "BackendCorrectnessTest" has a relative path.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/iDreamboat/Documents/Typora/ml_sklearn_tf/glow_no_env/glow/build_Debug
```

**Comment by idreamboat** [comment] 2018-11-28 02:51
> cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ../glow

```
ChangdeMacBook-Pro:build_Debug iDreamboat$ cmake  -G Ninja -DCMAKE_BUILD_TYPE=Debug ../../glow
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.7 or higher is required.  You are running version 3.5.1


-- Configuring incomplete, errors occurred!
See also "/Users/iDreamboat/Documents/Typora/ml_sklearn_tf/glow_no_env/glow/build_Debug/CMakeFiles/CMakeOutput.log".
See also "/Users/iDreamboat/Documents/Typora/ml_sklearn_tf/glow_no_env/glow/build_Debug/CMakeFiles/CMakeError.log".
```
there are more than one version of cmake in my mac, so i need specify the right version of cmake

**Comment by idreamboat** [comment] 2018-11-28 03:01
and CMakeOutput.log and  CMakeError.log as follow
[CMakeError.log](https://github.com/pytorch/glow/files/2622648/CMakeError.log)
[CMakeOutput.log](https://github.com/pytorch/glow/files/2622649/CMakeOutput.log)

**Comment by bertmaher** [comment] 2018-11-28 04:31
Anyways, it seems like you have a libpng installed in /Library/Frameworks, and that cmake is picking it up first.  I think this is not an uncommon problem, since googling the framework name turns up things like: https://github.com/torch/image/issues/137.  You could try moving the framework away, configuring glow, and then moving it back.

**Comment by idreamboat** [comment] 2018-11-28 06:33
> /Library/Frameworks
i rename /Library/Frameworks/libpng.framework as libpng_bkup.framework
but

'ChangdeMacBook-Pro:build_Debug iDreamboat$ ninja all
ninja: error: '/Library/Frameworks/libpng.framework', needed by 'lib/Onnxifi/libonnxifi-glow.dylib', missing and no known rule to make it'

**Comment by bertmaher** [comment] 2018-11-29 06:08
Yeah, if you just re-run ninja you're still using cached cmake variables.  You need to delete your build directory, re-create it, re-run cmake, and then re-run ninja.

**Comment by idreamboat** [comment] 2018-11-29 07:42
> Yeah, if you just re-run ninja you're still using cached cmake variables. You need to delete your build directory, re-create it, re-run cmake, and then re-run ninja.

yes, i follow your step,
![image](https://user-images.githubusercontent.com/14039458/49206412-f1d68780-f3ec-11e8-8180-b51ca08688ea.png)

![image](https://user-images.githubusercontent.com/14039458/49206495-382be680-f3ed-11e8-9408-7f9723e2d93e.png)
but this error message seems need this **libpng.framework**
`ninja: error: '/Library/Frameworks/libpng.framework', needed by 'lib/Onnxifi/libonnxifi-glow.dylib', missing and no known rule to make it`

**Comment by bertmaher** [comment] 2018-12-18 19:02
I'm 98% sure this issue is due to local configuration issues rather than anything specific to Glow.  I'm sorry we weren't able to find a resolution, but this is life for C++ developers -- building C++ is hard :-(.  You might try using Docker to build; a contributor recently added `utils/docker/Dockerfile` that works well for me.

**Closed by bertmaher** 2018-12-18 19:02 UTC

**Comment by anguoyang** [comment] 2020-02-04 07:11
@bertmaher yes, you are right, it is not related with Glow, I met same issue when compiling mxnet with TVM support, anyone else find a solution?
