### ISSUE TITLE
Automatic RNN state tracking is not working / Recurrent projection weights are optimized out

### ISSUE THREAD

**Issue by oleksii-abramenko** [pytorch/glow#4782] opened 2020-08-06 18:04 UTC
Hello community,

Please consider toy neural net defined in the following way:
```
class RNNTest(nn.Module):
    def __init__(self):
        super(RNNTest, self).__init__()
        self.rnn = nn.RNN(60, 60, num_layers=3)

    def forward(self, x):
        x, _ = self.rnn(x)
        return x
```
**Total number of params for this model is 21960**

It is exported to ONNX using the following method:
```

model = RNNTest()
dummy_input = torch.randn(1,1,60)
model = model.eval()
torch.onnx.export(model, (dummy_input,), "test.onnx",
                  input_names=['data'] ,training=torch.onnx.TrainingMode.EVAL)

```
It is compiled with GLOW by the following command:

`./model-compiler -model test.onnx -emit-bundle test_dir  -model-input=data,float,[1,1,60] -backend=CPU -target=arm -mcpu=cortex-m4 -float-abi=hard`

After exporting, it is evident that file **test.weights.bin** has size 44,736, which is not expected because it should be at least 21960*4bytes = 87840 bytes, given the fact that all parameters are floats.

Upon further inspection it seems like recurrent the projection weights have been optimized out. I think this may happen because compiler sees that initial state of RNN is not provided(which means it is zero) and doesn't have effect on further computation.

At the same time I see that GLOW automatically creates and exposes placeholders for hidden states to enable easy state manipulation and automatic tracking. But this is not helpful at this time because RNN is not working properly due to the weights being optimized out.

In order to prevent recurrent projection weights from being optimized out one need to modify the model to provide hidden state explicitly as a placeholder:

```
class RNNTest(nn.Module):
    def __init__(self):
        super(RNNTest, self).__init__()
        self.rnn = nn.RNN(60, 60, num_layers=3)

    def forward(self, x, h):
        x, _ = self.rnn(x, h)
        return x

dummy_input = torch.randn(1,1,60)
dummy_hidden = torch.randn(3, 1, 60)
inf_model = inf_model.eval()
torch.onnx.export(inf_model, (dummy_input, dummy_hidden), "test.onnx",
                  input_names=['data', 'hidden'] ,training=torch.onnx.TrainingMode.EVAL)

./model-compiler -model test.onnx -emit-bundle test_dir  -model-input=data,float,[1,1,60] -model-input=hidden,float,[3,1,60] -backend=CPU -target=arm -mcpu=cortex-m4 -float-abi=hard
```

In this case upon the conversion our test.weights.bin will have size of 87,936 bytes, so that the recurrent projection matrix is not optimized out.

**So the question is:** Why do you automatically create and expose placeholders for hidden states, if it is anyway required to provide your own placeholder for hidden state in order to prevent graph optimization? And in this case one cannot track states automatically, it is required to do manual memcpy() to copy hidden states from your automatic placeholders to the input placeholder "hidden"

Is there any way how to prevent compiler from optimizing out the recurrent projection when the hidden state is not explicitly provided as input? This will allow to take advantages of your "automatic hidden state tracking" mechanism.

Thanks in advance!

**Comment by mciprian13** [comment] 2020-08-07 09:16
@oleksii-abramenko Can you provide the ONNX model you use to investigate? Thanks!

**Comment by oleksii-abramenko** [comment] 2020-08-10 20:15
@mciprian13 

Please find attached the ONNX model.
[test.zip](https://github.com/pytorch/glow/files/5053144/test.zip)

**Comment by mciprian13** [comment] 2020-08-26 11:30
@oleksii-abramenko Indeed I reproduced your observations:
- What happens is that your model explicitly sets the initial states of the RNN modules to 0 meaning that the **R** weights are optimized out by Glow (which makes sense in my opinion).
- Indeed the total number of weights for your model is 3 x (60 x 60 + 60 x 60 + 120) = 21960 parameters but the **R** weights optimized out this gives 3 x (60 x 60 + 120) = 11160 parameters which is what you observe.
- I pushed a PR with a modification here #4830 such that the RNN states are no longer exported by default.
You can solve the problem in two ways:
1. Redefine the model such that the state placeholders are explicitly exported by the mode, such that you can manipulate them any way you want.
2. With the PR I mentioned you can compile the model with the extra-option `onnx-export-rnn-states` such that the RNN states are exported as placeholders (and automatically tracked) regardless of whether they are explicitly set or not in the model. In this case the optimization of the recurrent weights dissapears.

**Comment by oleksii-abramenko** [comment] 2020-08-26 18:41
Thanks! I have tried 1) already, it seems working.

Regarding 2), maybe I am missing something, but the model is already exporting placeholders for hidden states. For example, please take a look here: https://github.com/pytorch/glow/blob/54c7625053bfb14955c4402ab8d9bca85195d53c/lib/Importer/ONNXModelLoader.cpp#L2857 , in the function ONNXModelLoader::loadRNN it says:

  // We always create placeholders for the RNN state variable Y_h for the
  // following reasons:
  // - expose the RNN state in the graph interface for accessibility (set
  //   desired state, reset state, watch the state being updated automatically).
  // - since the RNN cells are unrolled (no graph loop primitive available
  //   at this point), the optimal way to use the RNN within a model would be
  //   to have it defined with only 1 time step and have the loop in the top
  //   of the application while the RNN state will be automatically updated
  //   from one iteration (time step) to the next through the placeholders.


And indeed, the model is creating these placeholders **Y_h** for me already (before merging aforementioned PR), I can see them in the generated **.h** file.  **That is why I didn't provide placeholder for the initial state, because you are doing it automatically**. So the confusion was: why would you create those automatic placeholders **Y_h** if they are useless (due to the recurrent weights being optimized out) unless I provide my own placeholder.

**Comment by mciprian13** [comment] 2020-08-27 08:23
@oleksii-abramenko What happened is that the state placeholders were always created, the updated states were always stored in the placeholders but the state placeholders were used as input states only if the states were not explicitly set in the model (which was not the case in your model since the model explicitly set the state to 0).
With the new PR I mentioned what happens is that the state placeholders are always used as input states whether the states are set explicitly or not. With that PR I actually tested your model and when using `-onnx-export-rnn-states` the placeholders are used both for input/output (the state is correctly tracked) and the recurrent weights optimization is eliminated.

**Comment by jfix71** [comment] 2020-10-14 17:14
Seems like this is resolved, closing for now, feel free to reopen if needed.

**Closed by jfix71** 2020-10-14 17:14 UTC
