### ISSUE TITLE
image-classifier is not working on resnet18

### ISSUE THREAD

**Issue by ghost** [pytorch/glow#2837] opened 2019-05-01 16:34 UTC
Following the documentation in https://github.com/pytorch/glow/blob/master/docs/ModelLoader.md, I am able to export `resnet18` ONNX graph, but not able to build with the image classifier:

```
~/nn/xgmr/build/debug/bin $  ./image-classifier ~/nn/xgmr/tests/images/imagenet/cat_285.png -model=~/nn/xgmr/utils/resnet18.onnx -model-input-name=data -cpu -emit-bundle=../output
Model:~/nn/xgmr/utils/resnet18.onnx
Encountered an error, exiting.
file: ../../include/glow/Importer/CommonOperatorLoader.h line: 522 message: Non-constant shape tensors are unsupported by Glow.
```

**Comment by nickgg** [comment] 2019-05-01 23:41
Can you attach the ONNX file? It is true that we don't currently support non constant shapes, does resnet18 rely on them?

**Comment by wny-guy** [comment] 2019-05-02 18:11
@nickgg It looks like resnet relies on them. I am not sure. I think it may be better to generate the onnx file on your end to try to exactly reproduce the issue. To generate it:

```
export GLOW_PATH=~/glow/

cd ${GLOW_PATH}/utils

python export_onnx_model.py --model_name resnet18 --model_path resnet18.onnx --model_input_name data
```

That will produce `resnet18.onnx` in `${GLOW_PATH}/utils`.

**Comment by jfix71** [comment] 2019-05-02 18:44
So I took a look and it appears the problem is that the shapes are statically known, but we need constant prop to figure that out (related to #1469, but we need this to happen at graph building time instead of graph optimization time).

Right now Glow requires that the shape input to the Reshape be a Constant input. Instead the shape is built via a concat, 2 unsqueezes, a gather, and a shape.

<details>
 <summary>Click here to see the relevant pattern from the proto which I copied out.</summary>

```
node {
  output: "190"
  op_type: "Constant"
  attribute {
    name: "value"
    t {
      data_type: 7
      raw_data: "\000\000\000\000\000\000\000\000"
    }
    type: TENSOR
  }
}
node {
  input: "189"
  output: "191"
  op_type: "Shape"
}
node {
  input: "191"
  input: "190"
  output: "192"
  op_type: "Gather"
  attribute {
    name: "axis"
    i: 0
    type: INT
  }
}
node {
  output: "193"
  op_type: "Constant"
  attribute {
    name: "value"
    t {
      data_type: 7
      raw_data: "\377\377\377\377\377\377\377\377"
    }
    type: TENSOR
  }
}
node {
  input: "192"
  output: "194"
  op_type: "Unsqueeze"
  attribute {
    name: "axes"
    ints: 0
    type: INTS
  }
}
node {
  input: "193"
  output: "195"
  op_type: "Unsqueeze"
  attribute {
    name: "axes"
    ints: 0
    type: INTS
  }
}
node {
  input: "194"
  input: "195"
  output: "196"
  op_type: "Concat"
  attribute {
    name: "axis"
    i: 0
    type: INT
  }
}
node {
  input: "189"
  input: "196"
  output: "197"
  op_type: "Reshape"
}
```

</details>

If you want to run it without that fix, one easy workaround for now would be to simply figure out what the reshape shape should be and replace the above 196 output with a Constant of that shape. It shouldn't be too difficult, as there's just the single Reshape.

**Comment by jfix71** [comment] 2019-05-02 19:35
Note this is similar to https://github.com/pytorch/glow/issues/1580#issuecomment-418606504.

**Comment by MaratZakirov** [comment] 2019-06-25 14:32
> So I took a look and it appears the problem is that the shapes are statically known, but we need constant prop to figure that out (related to #1469, but we need this to happen at graph building time instead of graph optimization time).
> 
> Right now Glow requires that the shape input to the Reshape be a Constant input. Instead the shape is built via a concat, 2 unsqueezes, a gather, and a shape.
> Click here to see the relevant pattern from the proto which I copied out.
> 
> ```
> node {
>   output: "190"
>   op_type: "Constant"
>   attribute {
>     name: "value"
>     t {
>       data_type: 7
>       raw_data: "\000\000\000\000\000\000\000\000"
>     }
>     type: TENSOR
>   }
> }
> node {
>   input: "189"
>   output: "191"
>   op_type: "Shape"
> }
> node {
>   input: "191"
>   input: "190"
>   output: "192"
>   op_type: "Gather"
>   attribute {
>     name: "axis"
>     i: 0
>     type: INT
>   }
> }
> node {
>   output: "193"
>   op_type: "Constant"
>   attribute {
>     name: "value"
>     t {
>       data_type: 7
>       raw_data: "\377\377\377\377\377\377\377\377"
>     }
>     type: TENSOR
>   }
> }
> node {
>   input: "192"
>   output: "194"
>   op_type: "Unsqueeze"
>   attribute {
>     name: "axes"
>     ints: 0
>     type: INTS
>   }
> }
> node {
>   input: "193"
>   output: "195"
>   op_type: "Unsqueeze"
>   attribute {
>     name: "axes"
>     ints: 0
>     type: INTS
>   }
> }
> node {
>   input: "194"
>   input: "195"
>   output: "196"
>   op_type: "Concat"
>   attribute {
>     name: "axis"
>     i: 0
>     type: INT
>   }
> }
> node {
>   input: "189"
>   input: "196"
>   output: "197"
>   op_type: "Reshape"
> }
> ```
> 
> If you want to run it without that fix, one easy workaround for now would be to simply figure out what the reshape shape should be and replace the above 196 output with a Constant of that shape. It shouldn't be too difficult, as there's just the single Reshape.

What fix did you mentioned?
How should I replace this Reshape node? Using what tool?

**Comment by MaratZakirov** [comment] 2019-06-25 15:02
I also must state that this issue in not only for resnet18 in my case all models follow same invalid (in my opinion) behavior

**Comment by jfix71** [comment] 2019-06-25 21:30
>What fix did you mentioned?
>How should I replace this Reshape node? Using what tool?

You could simply modify the protobuf by hand, adding in a Constant of the correct shape and using it in place of the other non-Constant ops. Alternatively you could wait for the Constant propagation PR #3141 to land and extend it if necessary for your needs.

>I also must state that this issue in not only for resnet18 in my case all models follow same invalid (in my opinion) behavior

This is not invalid -- it's valid/correct behavior based on the current limitations of Glow. Once the Constant propagation in the Loader PR lands then it will be handled better as we can better handle these sorts of patterns.

**Comment by MaratZakirov** [comment] 2019-06-26 08:43
How can I

> > What fix did you mentioned?
> > How should I replace this Reshape node? Using what tool?
> 
> You could simply modify the protobuf by hand, adding in a Constant of the correct shape and using it in place of the other non-Constant ops. Alternatively you could wait for the Constant propagation PR #3141 to land and extend it if necessary for your needs.
> 
> > I also must state that this issue in not only for resnet18 in my case all models follow same invalid (in my opinion) behavior
> 
> This is not invalid -- it's valid/correct behavior based on the current limitations of Glow. Once the Constant propagation in the Loader PR lands then it will be handled better as we can better handle these sorts of patterns.

How can I edit protobuf file?

**Comment by jfix71** [comment] 2019-06-26 17:05
You can use `protoc` to decode it in a text file. You can use the proto definition file `onnx.proto` found in `thirdparty/onnx/onnx/onnx.proto`. Then you can modify the text file and load that into Glow, or encode back to a pb if you want.

**Comment by et-nivard** [comment] 2021-02-22 09:52
I'm running an ONNX Resnet50 model and the following assert is firing when I try batch > 1 (for instance minibatch = 2):
`F0219 14:30:45.274777   140 Graph.cpp:1278] Check failed: TR->size() == input.getType()->size() (2048 vs. 4096) Reshape to a different size`
Looking at previous issues I found this one that seems related. There is a Reshape node that seems to be missing proper operand shape. I see that the fix #3141 already landed but the issue seems to persist. Is this expected? Or the fix was not totally generic?

**Comment by jfix71** [comment] 2021-02-22 17:36
@et-nivard I think this is a different issue, see https://github.com/pytorch/glow/issues/2195 and https://github.com/onnx/models/issues/114. In general the ONNX exporter often includes reshapes built in which are explicit on the batch size and thus restrict changing the batch size. We could try to override this inside of Glow but it's perhaps a little hacky and currently not supported.

**Comment by jfix71** [comment] 2021-02-22 17:36
Original issue is now fixed thanks to constant folding support that we now have, so I am closing this issue.

**Closed by jfix71** 2021-02-22 17:36 UTC
